### PR TITLE
Did some work on the path_redirect_import module.

### PR DESCRIPTION
**Pull request by bartvanhoutte**

### CODE REVIEW

**Comment by tjwelde** [comment]
Hi, thanks for your contribution. Another contributor opened a PR with a complete overhaul of the module: https://github.com/BurdaMagazinOrg/module-path_redirect_import/pull/3
He also added language support, but I like your idea of checking for valid language.
Does the language_manager only return installed languages, or really all supported languages?

**Comment by tjwelde** [comment]
We should also keep the composer file.

**Comment by tjwelde** [comment]
Can you also have a look at the PR https://github.com/BurdaMagazinOrg/module-path_redirect_import/pull/3 and comment, if something is missing?

**Comment by bartvanhoutte** [comment]
PR #3 looks good, let's use that one instead of this one.

I'll see if I can find some time to go through it more thoroughly. I've already made a PR for composer.json.

**Pull request closed without merging**
